### ISSUE TITLE
Documentation for "1. forduló"

### ISSUE THREAD

**Issue by luczia06** [luczia06/bbb_2023#9]

**Comment by randomUSR56** [comment]
![cristiano-ronaldo-drinking](https://github.com/luczia06/bbb_2023/assets/90837272/22b8ffc7-c8dc-4d9f-906f-13fb394a9342)

**Comment by luczia06** [comment]
![autism-intensifies-whoa](https://github.com/luczia06/bbb_2023/assets/91258977/7fb8ca48-dfa2-44d7-afc3-587fc1e3a05a)
![steamuserimages-a akamaihd](https://github.com/luczia06/bbb_2023/assets/91258977/1624212b-b777-421f-8acb-2ffd92a5461e)
